//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PANTALLACIP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bd_AgviajesEntities : DbContext
    {
        public bd_AgviajesEntities()
            : base("name=bd_AgviajesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<pantalla_Result> pantalla()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pantalla_Result>("pantalla");
        }
    
        public virtual ObjectResult<Pantalla2_Result> Pantalla2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pantalla2_Result>("Pantalla2");
        }
    
        public virtual ObjectResult<pantalla3_Result> pantalla3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pantalla3_Result>("pantalla3");
        }
    
        public virtual ObjectResult<VENTASPORMES_Result> VENTASPORMES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VENTASPORMES_Result>("VENTASPORMES");
        }
    
        public virtual ObjectResult<sp_pantalla_facturada_Result> sp_pantalla_facturada()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_pantalla_facturada_Result>("sp_pantalla_facturada");
        }
    
        public virtual ObjectResult<pantalla_facturada_Result> pantalla_facturada()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pantalla_facturada_Result>("pantalla_facturada");
        }
    }
}
